name: pytorch
dependencies:
- python=3.6
- pip=19.3
- pip:
  - torch==1.8.1
  - torchvision==0.8.2
  - torchautio==0.8.1
  - jupyter==1.0.0
  - matplotlib==2.2.2
  - pandas==0.23.4
  - tqdm==4.60.0
  - torchtext===0.9.1
  - opencv-python===4.5.2.52
  - Pillow==8.2.0
  - Flask==2.0.1
